### ISSUE TITLE
proposal: Add log.NullLogger

### ISSUE THREAD

**Issue by shazow** [alexcesaro/log#6]
I'd like to propose adding a `NullLogger` instance to the `log` package which implements a no-op version of `log.Logger`.

This is obviously a minor improvement, but I run into it often enough that I figure it's worth asking. :) I'd be happy to do a PR for this if you'd like.

## Use case

In all of my subpackages, I like to use a package-global log.Logger instance, it typically looks like this:

```go
package foo

import (
	"io/ioutil"

	"github.com/alexcesaro/log"
	"github.com/alexcesaro/log/golog"
)

var logger log.Logger

func SetLogger(l log.Logger) {
	logger = l
}

func init() {
	// Set a default null logger
	SetLogger(golog.New(ioutil.Discard, log.None))
}
```

Ideally, I'd like for this boilerplate file to be more like:

```go
package foo

import "github.com/alexcesaro/log"

var logger log.Logger = log.NullLogger

func SetLogger(l log.Logger) {
	logger = l
}
```

**Comment by alexcesaro** [comment]
You can currently simplify a bit:
```
package foo

import "github.com/alexcesaro/log"

var logger log.Logger = golog.New(ioutil.Discard, log.None)

func SetLogger(l log.Logger) {
    logger = l
}
```

But I'm fine with a `log.NullLogger`. I remember hesitating adding it once.

**Comment by shazow** [comment]
You're right, not sure why I've been fiddling with `init`. One correction, you'd still need to import golog in addition.

I'll try to put together a PR for log.NullLogger. :)

Btw, thanks again for making such a great stable/complete logging library. It's amazing how long I've been using it without really running into any problems, and only a tiny bit of room for improvement.

**Comment by alexcesaro** [comment]
Thank you very much for your kind words :smile:

Lately I have been working on a new logger. It will be more targeted at web apps than to CLI like your ssh-chat. But maybe you will find it interesting. I'll tell you when it is ready.

**Comment by shazow** [comment]
Indeed, would love to check it out!
